Import("env")

localenv = env.Clone()
localenv["LIBS"].append("dedupv1_base")
localenv["LIBS"].append("dedupv1_core")

dedupv1d_src = filter(lambda s: not s.path.endswith("dedupv1d_app.cc"),
  Glob("src/*.cc") + Glob("resources/*.cc"))

dedupv1d_lib = localenv.SharedLibrary("dedupv1d",
  dedupv1d_src,
  CPPPATH = localenv["CPPPATH"] + [
  "#core/include",
  "#core/resources",
  "#base/include",
  "#base/resources",
  "#dedupv1d/include",
  "#dedupv1d/resources"])
Return("dedupv1d_lib")
