# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dedupv1_base.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dedupv1_base.proto',
  package='',
  serialized_pb='\n\x12\x64\x65\x64upv1_base.proto\"d\n\x18\x44iskHashIndexLogfileData\x12\x11\n\tpage_size\x18\x02 \x01(\r\x12\x0c\n\x04size\x18\x03 \x01(\x04\x12\x10\n\x08\x66ilename\x18\x04 \x03(\t\x12\x15\n\roverflow_area\x18\x05 \x01(\x08\"M\n\x10\x44iskHashPageData\x12\x0b\n\x03\x63rc\x18\x02 \x01(\x07\x12\x13\n\x0b\x65ntry_count\x18\x03 \x01(\r\x12\x17\n\x08overflow\x18\x04 \x01(\x08:\x05\x66\x61lse\"\x92\x01\n\x1b\x44iskHashTransactionPageData\x12\x11\n\tbucket_id\x18\x01 \x01(\x04\x12\x14\n\x0coriginal_crc\x18\x02 \x01(\x07\x12\x17\n\x0ftransaction_crc\x18\x03 \x01(\x07\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x12\n\nitem_count\x18\x05 \x01(\x04\x12\x0f\n\x07version\x18\x06 \x01(\x04\"E\n\x12\x46ixedIndexMetaData\x12\r\n\x05width\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x12\n\nfile_count\x18\x03 \x01(\x04\"|\n\x14\x46ixedIndexBucketData\x12\x0b\n\x03key\x18\x04 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12)\n\x05state\x18\x02 \x01(\x0e\x32\x1a.FixedIndexBucketStateData\x12\x11\n\tcrc_bytes\x18\x03 \x01(\x0c\x12\x0b\n\x03\x63rc\x18\x05 \x01(\x07\"\x14\n\x07IntData\x12\t\n\x01i\x18\x01 \x01(\x04\"N\n\nBitmapData\x12\x0c\n\x04size\x18\x01 \x01(\x04\x12\x12\n\nclean_bits\x18\x02 \x01(\x04\x12\x11\n\tpage_size\x18\x03 \x01(\x04\x12\x0b\n\x03\x63rc\x18\x04 \x01(\r\"+\n\x0e\x42itmapPageData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0b\n\x03\x63rc\x18\x02 \x01(\r\" \n\x0bRawByteData\x12\x11\n\traw_value\x18\x01 \x01(\t*W\n\x19\x46ixedIndexBucketStateData\x12\x1b\n\x17\x46IXED_INDEX_STATE_VALID\x10\x00\x12\x1d\n\x19\x46IXED_INDEX_STATE_INVALID\x10\x01')

_FIXEDINDEXBUCKETSTATEDATA = _descriptor.EnumDescriptor(
  name='FixedIndexBucketStateData',
  full_name='FixedIndexBucketStateData',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIXED_INDEX_STATE_VALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIXED_INDEX_STATE_INVALID', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=730,
  serialized_end=817,
)

FixedIndexBucketStateData = enum_type_wrapper.EnumTypeWrapper(_FIXEDINDEXBUCKETSTATEDATA)
FIXED_INDEX_STATE_VALID = 0
FIXED_INDEX_STATE_INVALID = 1



_DISKHASHINDEXLOGFILEDATA = _descriptor.Descriptor(
  name='DiskHashIndexLogfileData',
  full_name='DiskHashIndexLogfileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page_size', full_name='DiskHashIndexLogfileData.page_size', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='DiskHashIndexLogfileData.size', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='DiskHashIndexLogfileData.filename', index=2,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overflow_area', full_name='DiskHashIndexLogfileData.overflow_area', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=122,
)


_DISKHASHPAGEDATA = _descriptor.Descriptor(
  name='DiskHashPageData',
  full_name='DiskHashPageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='crc', full_name='DiskHashPageData.crc', index=0,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entry_count', full_name='DiskHashPageData.entry_count', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overflow', full_name='DiskHashPageData.overflow', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=124,
  serialized_end=201,
)


_DISKHASHTRANSACTIONPAGEDATA = _descriptor.Descriptor(
  name='DiskHashTransactionPageData',
  full_name='DiskHashTransactionPageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket_id', full_name='DiskHashTransactionPageData.bucket_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='original_crc', full_name='DiskHashTransactionPageData.original_crc', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transaction_crc', full_name='DiskHashTransactionPageData.transaction_crc', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='DiskHashTransactionPageData.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_count', full_name='DiskHashTransactionPageData.item_count', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='DiskHashTransactionPageData.version', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=204,
  serialized_end=350,
)


_FIXEDINDEXMETADATA = _descriptor.Descriptor(
  name='FixedIndexMetaData',
  full_name='FixedIndexMetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='FixedIndexMetaData.width', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='FixedIndexMetaData.size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_count', full_name='FixedIndexMetaData.file_count', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=352,
  serialized_end=421,
)


_FIXEDINDEXBUCKETDATA = _descriptor.Descriptor(
  name='FixedIndexBucketData',
  full_name='FixedIndexBucketData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='FixedIndexBucketData.key', index=0,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='FixedIndexBucketData.data', index=1,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='FixedIndexBucketData.state', index=2,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crc_bytes', full_name='FixedIndexBucketData.crc_bytes', index=3,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crc', full_name='FixedIndexBucketData.crc', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=423,
  serialized_end=547,
)


_INTDATA = _descriptor.Descriptor(
  name='IntData',
  full_name='IntData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='i', full_name='IntData.i', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=549,
  serialized_end=569,
)


_BITMAPDATA = _descriptor.Descriptor(
  name='BitmapData',
  full_name='BitmapData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='BitmapData.size', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clean_bits', full_name='BitmapData.clean_bits', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='BitmapData.page_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crc', full_name='BitmapData.crc', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=571,
  serialized_end=649,
)


_BITMAPPAGEDATA = _descriptor.Descriptor(
  name='BitmapPageData',
  full_name='BitmapPageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='BitmapPageData.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crc', full_name='BitmapPageData.crc', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=651,
  serialized_end=694,
)


_RAWBYTEDATA = _descriptor.Descriptor(
  name='RawByteData',
  full_name='RawByteData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_value', full_name='RawByteData.raw_value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=696,
  serialized_end=728,
)

_FIXEDINDEXBUCKETDATA.fields_by_name['state'].enum_type = _FIXEDINDEXBUCKETSTATEDATA
DESCRIPTOR.message_types_by_name['DiskHashIndexLogfileData'] = _DISKHASHINDEXLOGFILEDATA
DESCRIPTOR.message_types_by_name['DiskHashPageData'] = _DISKHASHPAGEDATA
DESCRIPTOR.message_types_by_name['DiskHashTransactionPageData'] = _DISKHASHTRANSACTIONPAGEDATA
DESCRIPTOR.message_types_by_name['FixedIndexMetaData'] = _FIXEDINDEXMETADATA
DESCRIPTOR.message_types_by_name['FixedIndexBucketData'] = _FIXEDINDEXBUCKETDATA
DESCRIPTOR.message_types_by_name['IntData'] = _INTDATA
DESCRIPTOR.message_types_by_name['BitmapData'] = _BITMAPDATA
DESCRIPTOR.message_types_by_name['BitmapPageData'] = _BITMAPPAGEDATA
DESCRIPTOR.message_types_by_name['RawByteData'] = _RAWBYTEDATA

class DiskHashIndexLogfileData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DISKHASHINDEXLOGFILEDATA

  # @@protoc_insertion_point(class_scope:DiskHashIndexLogfileData)

class DiskHashPageData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DISKHASHPAGEDATA

  # @@protoc_insertion_point(class_scope:DiskHashPageData)

class DiskHashTransactionPageData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DISKHASHTRANSACTIONPAGEDATA

  # @@protoc_insertion_point(class_scope:DiskHashTransactionPageData)

class FixedIndexMetaData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FIXEDINDEXMETADATA

  # @@protoc_insertion_point(class_scope:FixedIndexMetaData)

class FixedIndexBucketData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FIXEDINDEXBUCKETDATA

  # @@protoc_insertion_point(class_scope:FixedIndexBucketData)

class IntData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTDATA

  # @@protoc_insertion_point(class_scope:IntData)

class BitmapData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BITMAPDATA

  # @@protoc_insertion_point(class_scope:BitmapData)

class BitmapPageData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BITMAPPAGEDATA

  # @@protoc_insertion_point(class_scope:BitmapPageData)

class RawByteData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RAWBYTEDATA

  # @@protoc_insertion_point(class_scope:RawByteData)


# @@protoc_insertion_point(module_scope)
