from os.path import join, basename
import glob

project = "dedupv1_passwd"

Import("env")

localenv = env.Clone()
localenv["LIBS"].append("dedupv1_base")

dedupv1_base_includes = ["#base/include"]

dedupv1_passwd = localenv.Program(project,
  source = Glob("src/*.cc"),
  CPPPATH = localenv["CPPPATH"] + dedupv1_base_includes)

localenv.Alias("all", project)
localenv.Default(project)
Return("dedupv1_passwd")
