from os.path import join, basename
import glob

project = "dedupv1_replay"

Import("env", 
  "build_mode",
  "dedupv1_base_lib",
  "dedupv1_core_lib",
  "dedupv1d_lib")

localenv = env.Clone()
localenv["LIBS"].append(dedupv1_base_lib)
localenv["LIBS"].append(dedupv1_core_lib)
localenv["LIBS"].append(dedupv1d_lib)

dedupv1_includes = ["#core/include",
  "#core/resources",
  "#base/include",
  "#base/resources",
  "#dedupv1d/include",
  "#dedupv1d/resources"]

dedupv1_replay = localenv.Program(project, 
  source = Glob("src/*.cc"), 
  CPPPATH = localenv["CPPPATH"] + dedupv1_includes)

localenv.Alias("all", project)
localenv.Default(project)
Return("dedupv1_replay")
