from os.path import join, basename
import glob

project = "dedupv1_debug"

Import("env")

localenv = env.Clone()

conf = Configure(localenv)
if not conf.CheckLib("linenoise"):
  Exit(1)
localenv = conf.Finish()
localenv["LIBS"].append("dedupv1_base")
localenv["LIBS"].append("dedupv1_core")
localenv["LIBS"].append("dedupv1d")

dedupv1_includes = ["#core/include",
  "#core/resources",
  "#base/include",
  "#base/resources",
  "#dedupv1d/include",
  "#dedupv1d/resources"]

dedupv1_debug = localenv.Program(project, 
  source = Glob("src/*.cc"), 
  CPPPATH = localenv["CPPPATH"] + dedupv1_includes)

localenv.Alias("all", project)
localenv.Default(project)
Return("dedupv1_debug")
